name = "iprodan-dev"
compatibility_date = "2026-02-21"
compatibility_flags = ["nodejs_compat"]

main = "./dist/_worker.js/index.js"

assets = { directory = "./dist", binding = "ASSETS" }
routes = [{ pattern = "iprodan.dev", custom_domain = true }]

# Optional: Enable minification
minify = true
placement = { mode = "smart" }
